### ISSUE TITLE
Uncaught TypeError: Cannot read property 'list' of null

### ISSUE THREAD

**Issue by mschan** [thislooksfun/google-repo-package#2]
[Enter steps to reproduce:]

1. Not working with nuclide

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [google-repo](https://github.com/thislooksfun/google-repo-package) package 1.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'list' of null

```
At /Users/mschan/.atom/packages/google-repo/lib/main.coffee:54

TypeError: Cannot read property 'list' of null
    at Main.refresh (/packages/google-repo/lib/main.coffee:54:25)
    at /packages/google-repo/lib/main.coffee:22:87)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -7:59.6.0 core:paste (input.hidden-input)
  3x -7:56.5.0 core:backspace (input.hidden-input)
     -3:54 core:confirm (input.hidden-input)
     -3:06.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:50.2.0 nuclide-file-tree:remove-project-folder-selection (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-directory.name.nuclide-file-tree-path.icon-nuclicon-file-directory-starred)
     -2:48.7.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:23.8.0 google-repo:refresh (input.hidden-input)
```

### Non-Core Packages

```
build 0.68.0 
build-make 0.13.0 
busy 0.7.0 
file-icons 2.1.11 
google-repo 1.5.0 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.71.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-luajit 1.2.0 
language-ocaml 1.9.5 
language-robot-framework 2.2.0 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
nuclide 0.245.0 
nuclide-format-js 0.0.41 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by thislooksfun** [comment]
Sorry, but this project is not actively maintained anymore as we have switched to using another system instead. You're free to submit a PR with a fix if you'd like.
