### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of undefined

### ISSUE THREAD

**Issue by akbennett** [thislooksfun/google-repo-package#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [google-repo](https://github.com/thislooksfun/google-repo-package) package 1.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of undefined

```
At /Users/akbennett/.atom/packages/google-repo/lib/main.coffee:54

TypeError: Cannot read property 'querySelector' of undefined
    at Main.refresh (/packages/google-repo/lib/main.coffee:54:33)
    at /packages/google-repo/lib/main.coffee:22:87)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1348:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:48.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  2x -1:40.5.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:32.8.0 core:confirm (input.hidden-input)
     -0:11 google-repo:refresh (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-typescript 11.0.10 
autocomplete-clang 0.11.4 
autocomplete-ctags 0.4.1 
build 0.69.0 
build-xcodebuild 0.2.0 
busy 0.7.0 
busy-signal 1.4.3 
compare-files 0.8.1 
file-icons 2.1.13 
google-repo 1.5.0 
google-repo-diff 1.1.1 
google-repo-diff-minimap 1.0.0 
intentions 1.1.5 
language-ini 1.19.0 
language-restructuredtext 1.1.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
tool-bar 1.1.0 
```

**Comment by thislooksfun** [comment]
This project is not actively maintained -- feel free to submit a PR with a fix.

**Comment by MichaelLisboa** [comment]
If that's the case, then 1) don't submit hobby projects to atom.io and 2) update readme to notify others that the project is no longer maintained.
